name: Build QMK firmware

on:
    push: {}
    workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: master

  publish:
    name: 'Publish'
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
            name: Firmware

      - name: Generate Release
        uses: softprops/action-gh-release@v2
        with:
            token: ${{ github.token }}
            name: Latest QMK Firmware
            fail_on_unmatched_files: false
            draft: false
            prerelease: false
            files: |
                **/*.hex
                **/*.bin
                **/*.uf2
